title: VUG
author: Neil Bartlett
email: njbartlett@gmail.com
description: Virtual OSGi Users' Group

# language to use in html tag, can be overriden by page.lang
# lang: en 

sass:
    style: compressed

# You can look up the color names at http://materializecss.com/color.html
colors:
    primary_dark: osgi-dark-blue
    primary_light: osgi-light-blue
    primary: osgi-blue
    accent: osgi-orange
    primary_text: grey-darken-4
    secondary_text: grey-darken-1
    inverse_text: white
    divider: grey-lighten-1
    secondaryBackground: grey-lighten-4

# path to logo without leading slash e.g. images/logo.png or just the file name if it is in the root directory
logo: logo.png

# Github data, if present there will be a GitHub button in the navbar
github_button:
  user: osgi-users-virtual
  project: osgi-users-virtual.github.io

# Twitter data, if present there will be a Twitter button in the navbar
twitter_button:
  user: osgi_vug

# any of these collections is used for nested pages
collections:
  landingpage:
    output: true
  resources:
    output: true
  posts:
    output: true
  faq:
    output: true